### ISSUE TITLE
Pglet running on Raspberry pi 4

### ISSUE THREAD

**Issue by R-fred** [pglet/pglet-python#25]
Out of curiosity I tried pglet on one of my raspberry pi 4 and it worked out of the box!

**Setup**
The raspberry pi is headless and serving the pglet websites
Firewall is switched off to facilitate the tests.
All tests run with the local parameter set to True to ensure the website is served from the Raspberry pi.

**Installation**
`pip3 install pglet` worked like a charm.
Installation was done in less than 30s.
Alternative libraries:
_Dash:_ installs Flask and many other dependencies incl. plotly for plotting, installs fine in 2-3 min.
_Streamlit:_ needs many, many dependencies to be installed incl. numpy and pandas. Fails to install.
Pglet is by far the easiest to install, which I am assuming will bring benefits in the future for maintainability of apps.

**Initial performance**
Running the embedded video example, to do app and the line chart example worked flawlessly and without delay.

<img width="600" alt="Screenshot 2021-05-25 at 20 25 52" src="https://user-images.githubusercontent.com/8479604/119550859-344c6580-bd99-11eb-8a14-964b5b912283.png">
<img width="600" alt="Screenshot 2021-05-25 at 20 35 51" src="https://user-images.githubusercontent.com/8479604/119550874-37475600-bd99-11eb-97c7-fd24fdf6f53e.png">
<img width="600" alt="Screenshot 2021-05-25 at 20 36 31" src="https://user-images.githubusercontent.com/8479604/119550876-37dfec80-bd99-11eb-9f6c-8fce46d7e4cf.png">

**Comment by FeodorFitsner** [comment]
Cool, thank you for the update! There could be a lot of use cases by running Pglet on Raspberry!
