### ISSUE TITLE
Unable to install pglet in enterprise setting

### ISSUE THREAD

**Issue by R-fred** [pglet/pglet-python#26]
I tried installing pglet-python in a docker container in our company's kubernetes cluster.
I had an issue with the current way pglet itself is installed.

I narrowed it down to the download from github failing.

Would it make sense to have pglet in the python package itself? It would be a very easy solution for me :). Whether it makes sense for you is another story.

**Comment by FeodorFitsner** [comment]
Sure, it makes sense. Will do that in the next Python module update (today/tomorrow).

**Comment by FeodorFitsner** [comment]
A new version of pglet module has been released which now includes pglet binaries for various platforms: https://pypi.org/project/pglet/0.4.4/

Let me know how it worked for you.

**Comment by R-fred** [comment]
I tried first on MacBook Air M1 and Raspberry pi (running Ubuntu 20.04.2 LTS) and both seem to work without a problem. On Monday I will try to install pglet in my work setting, I'll give you feedback on that issue then.
