### ISSUE TITLE
Allow to set port to serve app in the pglet.app() function

### ISSUE THREAD

**Issue by R-fred** [pglet/pglet-python#34]
It would be great to have the possibility to set the port for serving the application. This would help a lot in case of deployments on Kubernetes or similar.

**Comment by FeodorFitsner** [comment]
You can set port with `PGLET_SERVER_PORT` environment variable. Please give it a try and let me know how that worked.

**Comment by R-fred** [comment]
This worked locally on my MacBook Air M1. On my work windows PC it didn't seem to work, but maybe because I cannot change the system environment variables, only the user environment variables.

```
os.environ["PGLET_SERVER_PORT"] = "8231"
print(os.environ["PGLET_SERVER_PORT"])
```

Result:
`http://localhost:8231/p/7d3d25b8-ed28-11eb-b034-1e00d11a5445`

I will check on our Kubernetes cluster and edit this post.
