### ISSUE TITLE
Running app locally throws Error

### ISSUE THREAD

**Issue by freeman91** [pglet/pglet-python#38]
Tried running locally: `pglet.app("dashboard", target=main, local=True)`
But I'm getting the following error: `Connect app error: unexpected EOF`

**Comment by FeodorFitsner** [comment]
Thanks for trying Pglet! Could you please submit the entire app example you are trying to run?

PS: We are still trying to better understand Pglet use cases, so may I ask where did you know about Pglet and what kind of app are you working on and what language? Thanks!

**Comment by FeodorFitsner** [comment]
Feel free to re-open this issue if you are still experiencing it with the latest version of Pglet.
