### ISSUE TITLE
Running the example todo app on Replit results in a fatal error

### ISSUE THREAD

**Issue by mikaelho** [pglet/pglet-python#39]
I have copied the todo app code from [here](https://github.com/pglet/examples/blob/main/python/todo/todo-complete.py).

If I run the code as is, I get the link in the replit console. The link opens the todo app in a separate browser tab, and the app works fine, except refreshing of changes is troublesome as discussed in another issue.

I would like to run the service from replit, but changing the last line as instructed in the tutorial to:
`pglet.app("index", target=main)`

... only results in this message in the console window:
`FATA[2021-12-07T20:35:39Z] Connect app error: Account or page name is reserved`

After trying various things, I am unable to try anything else because I am throttled regardless of whether I try to run with the above line or something else:
`FATA[2021-12-07T20:39:29Z] Connect app error: A limit of 10 new pages per hour has been reached`

**Comment by FeodorFitsner** [comment]
Thank you for trying Pglet!

With the latest 0.4.6 Python module there should be `local=True` argument added while running on Replit:

```python
pglet.app("index", target=main, local=True)
```

Complete working example: https://replit.com/@pglet/ToDo-web-app-in-Python#main.py

**Comment by mikaelho** [comment]
Thank you for the very fast reply! I can confirm that it with the `local=True` it runs "locally" in Replit for me as well.

Yesterday I did look at the code and also tried adding the `local` parameter, but did not see it working as it seems you need to refresh the Replit "browser window" at the right time to make it reconnect to the server after restarting the replit.
