### ISSUE TITLE
Python ToDo list web deployment raises TypeError

### ISSUE THREAD

**Issue by Rockwell70** [pglet/pglet-python#41]
Hello, I wrapped up the entire ToDo list example and all went well until I added "web=True" to the final app call line. It raises the following error: "TypeError: app() got an unexpected keyword argument 'web'"

I tried it on the complete example code from this repo and the same error was raised

[todo.txt](https://github.com/pglet/pglet-python/files/7689478/todo.txt)
.

**Comment by FeodorFitsner** [comment]
In the last version there is no `web` argument anymore as "web" mode is default. Instead, there is `local=True` to make it work locally. However, it looks like `web=True` is going to re-appear in the next version as we got feedback that pushing app to the web by default is kind of scarry for the initial experience.

**Comment by FeodorFitsner** [comment]
Local mode is default one, no need to use `local=True` anymore.
