### ISSUE TITLE
Report errors in a way that does not hide traceback information

### ISSUE THREAD

**Issue by mikaelho** [pglet/pglet-python#43]
This approach to reporting errors:
https://github.com/pglet/pglet-python/blob/fb46af7cb63c0209ca1ac764da71bd722693af22/pglet/pglet.py#L85

... hides the tracebacks, making it hard to locate simple errors without debugging.

Alternatives would be to print the traceback explicitly (`print(traceback.format_exc())`), or probably better, just `raise` after setting the error on page.

**Comment by FeodorFitsner** [comment]
Fair enough - thanks for the catch! I'm still new to Python 😳. I'm going to try `raise` approach.

**Comment by FeodorFitsner** [comment]
Oh, well, exception raised in a separated thread is not visible to the main one. `traceback.format_exc()` worked though.

**Comment by mikaelho** [comment]
Yes, sorry, did not check the wider context. You could subclass `Thread` and store & relay exceptions, but hard to see the added value.

As a workaround for anyone waiting for the next `pglet-python` release, you can `try-except` in the `main` function and `format_exc` the traceback.

**Comment by FeodorFitsner** [comment]
Sure, here you are: https://pypi.org/project/pglet/0.4.7/

**Comment by mikaelho** [comment]
Thanks 👍🏻
