### ISSUE TITLE
Possibility to dismiss a Panel programmatically

### ISSUE THREAD

**Issue by mikaelho** [pglet/pglet-python#44]
I would like to have OK/Cancel type behaviour in a Panel, where dismissing the panel in any way does not change any of my values, only a separate OK button does -- and then dismisses the Panel.

I did experiment with setting `open` to False (and updating), but that did not seem to do anything.

Looking at the code I could not find a way to send a dismiss event to the Panel, or a method to call to accomplish the same. Nor did the documentation on the server protocol hint to any support for this.

**Comment by FeodorFitsner** [comment]
Have you tried `.visible=False` (and `.update()`) to see if it has desired effect?

**Comment by FeodorFitsner** [comment]
OK, look at this example: https://replit.com/@pgletio/python-panel-example#main.py - you can toggle panel with "Open/Close panel". Is it what you need?
