### ISSUE TITLE
Nested panel handling

### ISSUE THREAD

**Issue by mikaelho** [pglet/pglet-python#45]
Trying to learn from my mistakes, here is a repl demonstrating the topic: https://replit.com/@mikaelho/Nested-panels

It looks like I am opening new panels, and I would expect that dismissing the panel shows me the one below, but it looks like they all get dismissed -- or more likely there ever was only one, reused.

I can only add the panel to the page, not e.g. to the previous panel.

If this is as designed, I can take it as a hard constraint, but in case this is an unexpected use case and/or unexpected behaviour, I would much appreciate to know if there is a reasonable fix or a workaround.

**Comment by FeodorFitsner** [comment]
Yep, Panels, Dialogs and other "surface" controls are overlays. No matter which place in the document tree you are adding them they are always shown on top of the document. Technically their content is attached at the end of DOM in an absolute positioned div.

You can simulate "nested" panels by maintaining a virtual list of them, or stack, and then just having only a "current" panel on the page. Take a look: https://replit.com/@pglet/Nested-panels#main.py - dismissing a panel replaces it with a previous one.

**Comment by mikaelho** [comment]
Thanks!

I gave it an honest try, and there is something funky here.

In your code I can only close the "first" panel if I close it immediately. If I open a couple of "nested" panels first, they close down in order, but I no longer can close the first one. I could not figure why, and ran a bit out of time.

I also tried a version where I retain Panels in the array instead of Panel controls. That also almost worked, but closing the first Panel remained an issue.

**Comment by FeodorFitsner** [comment]
...and I've updated mine to close the last Panel: https://replit.com/@pglet/Nested-panels#main.py

Replit is nice for quick hacks :)

**Comment by mikaelho** [comment]
Yes, in many ways Replit seems like the perfect thing for something quick, and pglet seems also perfect for those same kinds of things.

With the help of this discussion, I was able to have several panels by adding a Stack at the end of the contents of the previous panel acting as the "owner" of the next layer panel, i.e. no global objects, which is nice.
